apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "semgr8s.name" . }}
  labels:
    {{- include "semgr8s.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      {{- include "semgr8s.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.deployment.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "semgr8s.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccount: {{ include "semgr8s.serviceAccountName" . }}
      {{- with .Values.deployment.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.deployment.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          {{- with .Values.deployment.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          image: "{{ .Values.deployment.image.repository }}:{{ .Values.deployment.image.tag | default (print "v" .Chart.AppVersion) }}"
          imagePullPolicy: {{ .Values.deployment.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.deployment.containerPort }}
          resources:
            {{- toYaml .Values.deployment.resources | nindent 12 }}
          volumeMounts:
          - mountPath: /app/certs
            name: cert
            readOnly: true
          - mountPath: /.semgrep
            name: semgrep-config
            readOnly: false
          - mountPath: /.cache
            name: cache
            readOnly: false
          - mountPath: /app/rules
            name: rules
            readOnly: false
          - mountPath: /app/data
            name: data
            readOnly: false
          envFrom:
          - configMapRef:
              name: {{ include "semgr8s.envName" . }}
      volumes:
      - name: cert
        secret:
          secretName: {{ include "semgr8s.TLSName" . }}
      - name: semgrep-config
        emptyDir: {}
      - name: cache
        emptyDir: {}
      - name: rules
        emptyDir: {}
      - name: data
        emptyDir:
          medium: "Memory"
          sizeLimit: 1Mi
