apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "semgr8s.roleName" . }}
  labels:
    {{- include "semgr8s.labels" . | nindent 4 }}
rules:
- apiGroups: ["*"]
  resources: ["configmaps"]
  verbs: ["list", "get"]
