
{{ $currentScope := .}}
{{ range $path, $_ := .Files.Glob "rules/*" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "semgr8s.getFileName" $path | trimSuffix ".yaml" }}
  labels:
    {{- include "semgr8s.labels" $currentScope | nindent 4 }}
    semgr8s/rule: "true"
data:
  {{ include "semgr8s.getFileName" $path }}: |
  {{- $.Files.Get $path | nindent 4}}
---
{{ end }}