apiVersion: v1
kind: Service
metadata:
  name: {{ include "semgr8s.serviceName" . }}
  labels:
    {{- include "semgr8s.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.deployment.containerPort }}
  selector:
    {{- include "semgr8s.selectorLabels" . | nindent 4 }}
