# Project information
site_name: semgr8s - Semgrep-based Policy Controller for Kubernetes.

site_url: https://semgr8ns.github.io/semgr8s/
site_description: >-
    Admission controller to use your well-known publicly available or custom Semgrep rules to validate k8s resources before deployment to the cluster.

# Repository
repo_name: semgr8ns/semgr8s/
repo_url: https://github.com/semgr8ns/semgr8s
edit_uri: ""

# Company
copyright:  <a href="https://securesystems.de">Secure Systems Engineering GmbH</a> 


# Configuration
theme:
  language: en
  name: material
  custom_dir: docs/overrides
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: blue
      toggle:
        icon: material/brightness-auto
        name: system preference

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: blue
      toggle:
        icon: material/brightness-7
        name: light mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: blue
      toggle:
        icon: material/brightness-4
        name: dark mode
  font:
    text: Roboto
    code: Roboto Mono
  logo: 'assets/semgr8s-logo-single.png'
  favicon: 'assets/semgr8s-logo-single.png'
  features:
    - content.code.annotate
    - content.code.copy
    - content.code.select
    - navigation.top

# Extensions
markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - attr_list
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
        permalink: ⚓︎

# Plugins
plugins:
  - glightbox:
      skip_classes:
        - skip-lightbox

# Extras
extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js
  - javascripts/tablesort.js

# Customization
extra:
  version:
      provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/semgr8ns
      name: SSE on GitHub
    - icon: fontawesome/brands/docker
      link: https://ghcr.io/semgr8ns/semgr8s
      name: Semgr8s images on GHCR
    - icon: fontawesome/brands/medium
      link: https://medium.com/sse-blog
      name: SSE on Medium
    - icon: fontawesome/brands/youtube
      link: https://www.youtube.com/channel/UCReAmr98RzwYZeWG6CAwOhg
      name: SSE on YouTube
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/sse_gmbh
      name: SSE on Twitter
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/sse-secure-systems-engineering
      name: SSE on LinkedIn
    - icon: fontawesome/solid/link
      link: https://www.securesystems.de/
      name: SSE Website
    - icon: fontawesome/solid/envelope
      link: mailto:semgr8s@securesystems.de
      name: Email contact

# Page tree
nav:
  - Intro: README.md
  - concept.md
  - usage.md
  - Exemplary rules:
    - examples/template-rule.md
    - examples/template-autofix-rule.md
    - examples/forbidden-pod-label.md
    - examples/forbidden-workload-label.md
    - examples/forbidden-namespaced-label.md
  - Selected rules:
    - examples/deny-default-namespace.md
    - examples/restrict-image-registry.md
