apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "semgr8s.roleBindingName" . }}
  labels:
    {{- include "semgr8s.labels" . | nindent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ include "semgr8s.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: Role
  name: {{ include "semgr8s.roleName" . }}
  apiGroup: rbac.authorization.k8s.io