name: trivy-config
description: 'Run Trivy on config'
inputs:
  output:
    description: 'Trivy output either "sarif" (GITHUB_TOKEN with security-events:write) or print results as "table" and fail on error'
    required: false
runs:
  using: "composite"
  steps:
    - name: Create reports folder
      run: |
        mkdir reports
      shell: bash
    - name: Render Helm charts
      run: |
        mkdir deployment
        helm template charts/connaisseur > deployment/deployment.yaml
      shell: bash
    - name: Scan deployment.yaml
      uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # v0.12.0
      if: inputs.output == 'table'
      with:
        scan-type: "config"
        scan-ref: "deployment"
        format: 'table'
    - name: Scan Dockerfiles
      uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # v0.12.0
      if: inputs.output == 'table'
      with:
        scan-type: "config"
        scan-ref: "build"
        format: 'table'
    - name: Scan deployment.yaml
      uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # v0.12.0
      if: inputs.output == 'sarif'
      with:
        scan-type: "config"
        scan-ref: "deployment"
        format: 'sarif'
        output: 'reports/trivy-k8s-results.sarif'
    - name: Scan Dockerfiles
      uses: aquasecurity/trivy-action@fbd16365eb88e12433951383f5e99bd901fc618f # v0.12.0
      if: inputs.output == 'sarif'
      with:
        scan-type: "config"
        scan-ref: "build"
        format: 'sarif'
        output: 'reports/trivy-docker-results.sarif'
    - name: Upload
      uses: github/codeql-action/upload-sarif@32dc499307d133bb5085bae78498c0ac2cf762d5 # v2.2.5
      if: inputs.output == 'sarif'
      with:
        sarif_file: 'reports'
