name: sast

on:
  workflow_call:
    inputs:
      skip:
        description: "Want to skip running certain jobs 'none', 'non-required', 'all'?"
        type: string
        default: "none"
      output:
        description: 'Output either "sarif" (GITHUB_TOKEN with security-events:write) or print results as "table" and fail on error'
        type: string
        required: false
        default: 'sarif'

#permissions: {}  #TODO: reactivate for non-private

jobs:
  checkov:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'non-required' &&
      inputs.skip != 'all'
    #    permissions:  #TODO: reactivate for non-private
    #      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Render Helm charts
        run: |
          rm -rf test # remove 'test' folder from scan #TODO: fix once final
          rm -rf tests # remove 'tests' folder from scan
          mkdir deployment
          helm template charts/connaisseur > deployment/deployment.yaml
        shell: bash
      - name: Scan
        if: inputs.output == 'table'
        uses: bridgecrewio/checkov-action@558f721c4bd65a6fc59b02448ffc792eb721cb9b # v12.2580.0
        with:
          output_format: cli
          soft_fail: false
      - name: Scan
        if: inputs.output == 'sarif'
        uses: bridgecrewio/checkov-action@558f721c4bd65a6fc59b02448ffc792eb721cb9b # v12.2580.0
        with:
          output_file_path: console,checkov-results.sarif
          output_format: cli,sarif
          soft_fail: true
      - name: Upload
        if: inputs.output == 'sarif'
        uses: github/codeql-action/upload-sarif@66b90a5db151a8042fa97405c6cf843bbe433f7b # v2.22.7
        with:
          sarif_file: checkov-results.sarif

  codeql:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'non-required' &&
      inputs.skip != 'all' &&
      inputs.output == 'sarif'
    #    permissions:  #TODO: reactivate for non-private
    #      pull-requests: read
    #      security-events: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Initialize CodeQL
        uses: github/codeql-action/init@66b90a5db151a8042fa97405c6cf843bbe433f7b # v2.22.7
        with:
          languages: 'go'
      - name: Analyze
        uses: github/codeql-action/analyze@66b90a5db151a8042fa97405c6cf843bbe433f7b # v2.22.7
  
  golangci-lint:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'all'
    #    permissions:  #TODO: reactivate for non-private
    #      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - uses: actions/setup-go@93397bea11091df50f3d7e59dc26a7711a8bcfbe # v4.1.0
        with:
          cache: false
          go-version: '1.21'
      - name: Analyze
        uses: golangci/golangci-lint-action@3a919529898de77ec3da873e3063ca4b10e7f5cc # v3.7.0
        with:
          version: latest
          args: '--timeout=10m --skip-dirs="test" --tests=false'

  gosec:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'all'
    #    permissions:  #TODO: reactivate for non-private
    #      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Analyze
        uses: securego/gosec@55d79496019a560e16e73e1948dee20a1fad631a # v2.18.2
        if: inputs.output == 'table'
        with:
          args: '-fmt text -exclude-dir=test -exclude-dir=tools ./...'
      - name: Analyze
        uses: securego/gosec@55d79496019a560e16e73e1948dee20a1fad631a # v2.18.2
        if: inputs.output == 'sarif'
        with:
          args: '-exclude-dir=test -exclude-dir=tools -no-fail -fmt sarif -out gosec-results.sarif ./...'
      - name: Upload
        uses: github/codeql-action/upload-sarif@66b90a5db151a8042fa97405c6cf843bbe433f7b # v2.22.7
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'gosec-results.sarif'

  hadolint:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'non-required' &&
      inputs.skip != 'all'
    #    permissions:  #TODO: reactivate for non-private
    #      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Scan
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        if: inputs.output == 'table'
        with:
          dockerfile: build/Dockerfile
          format: tty
          no-fail: false
      - name: Scan
        uses: hadolint/hadolint-action@54c9adbab1582c2ef04b2016b760714a4bfde3cf # v3.1.0
        if: inputs.output == 'sarif'
        with:
          dockerfile: build/Dockerfile
          format: sarif
          no-fail: true
          output-file: hadolint-results.sarif
      - name: Upload
        uses: github/codeql-action/upload-sarif@66b90a5db151a8042fa97405c6cf843bbe433f7b # v2.22.7
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'hadolint-results.sarif'

  kubelinter:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'non-required' &&
      inputs.skip != 'all'
    #    permissions:  #TODO: reactivate for non-private
    #      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Scan
        uses: stackrox/kube-linter-action@ca0d55b925470deb5b04b556e6c4276ea94d03c3 # v1.0.4
        if: inputs.output == 'table'
        with:
          config: .kube-linter/config.yaml
          directory: charts/connaisseur
          format: plain
      - name: Scan
        uses: stackrox/kube-linter-action@ca0d55b925470deb5b04b556e6c4276ea94d03c3 # v1.0.4
        if: inputs.output == 'sarif'
        with:
          config: .kube-linter/config.yaml
          directory: charts/connaisseur
          format: sarif
          output-file: kubelinter-results.sarif
      - name: Upload
        uses: github/codeql-action/upload-sarif@66b90a5db151a8042fa97405c6cf843bbe433f7b # v2.22.7
        if: inputs.output == 'sarif'
        with:
          sarif_file: 'kubelinter-results.sarif'

  semgrep:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'non-required' &&
      inputs.skip != 'all'
    #    permissions:  #TODO: reactivate for non-private
    #      security-events: write
    container:
      image: returntocorp/semgrep
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Scan
        if: inputs.output == 'table'
        run: semgrep ci --config=auto --suppress-errors --text
      - name: Scan
        if: inputs.output == 'sarif'
        run: semgrep ci --config=auto --suppress-errors --sarif --output=semgrep-results.sarif || exit 0
      - name: Upload
        uses: github/codeql-action/upload-sarif@66b90a5db151a8042fa97405c6cf843bbe433f7b # v2.22.7
        if: inputs.output == 'sarif'
        with:
          sarif_file: semgrep-results.sarif

  trivy-config-scan:
    name: trivy config
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'non-required' &&
      inputs.skip != 'all'
    #    permissions:  #TODO: reactivate for non-private
    #      security-events: write
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Run Trivy
        uses: ./.github/actions/trivy-config
        with:
          output: ${{ inputs.output }}

