name: integration-test

#permissions: {}  #TODO: reactivate for non-private

on:
  workflow_call:
    inputs:
      build_registry:
        description: "Workflow build registry used for testing"
        type: string
      repo_owner:
        description: 'Name of repository owner, e.g. "inputs.repo_owner" for ghcr.io'
        type: string
      build_image_repository:
        description: "Workflow build image used for testing, excluding the tag i.e. registry + repository"
        type: string
      build_tag:
        description: "Tag of build image used for testing"
        type: string
      skip:
        description: "Want to skip running certain jobs 'none', 'non-required', 'all'?"
        type: string
        default: "none"
      cosign_public_key:
        description: "Cosign public key used for signing the build image"
        type: string

env:
  IMAGEPULLSECRET: dockerconfigjson-ghcr

jobs:
  do-nothing:
    name: functional
    runs-on: ubuntu-latest
    if: inputs.skip != 'all'
    #    permissions:  #TODO: reactivate for non-private
    #      packages: read
    steps:
      - name: Do nothing
        run: |
          sleep 1
