name: build

permissions: {}

on:
  workflow_call:
    inputs:
      skip:
        description: "Want to skip running certain jobs 'none', 'non-required', 'all'?"
        type: string
        default: "none"
    outputs:
      chart_version: 
        description: "semgr8s Helm chart version"
        value: ${{ jobs.context.outputs.chart_version }}
      original_registry:
        description: "Public semgr8s registry"
        value: ${{ jobs.context.outputs.original_registry }}
      original_repo:
        description: "Public semgr8s repo"
        value: ${{ jobs.context.outputs.original_repo }}
      original_tag:
        description: "Current semgr8s tag, i.e. version"
        value: ${{ jobs.context.outputs.original_tag }}
      original_image:
        description: "Full semgr8s image reference, i.e. registry + repository + tag"
        value: ${{ jobs.context.outputs.original_image }}
      build_registry:
        description: "Workflow build registry used for testing"
        value: ${{ jobs.context.outputs.build_registry }}
      build_repo:
        description: "Workflow build repository used for testing"
        value: ${{ jobs.context.outputs.build_repo }}
      build_tag:
        description: "Workflow build tag used for testing (unique for each run)"
        value: ${{ jobs.context.outputs.build_tag }}
      branch_tag:
        description: "Branch tag used for all builds on branch"
        value: ${{ jobs.context.outputs.branch_tag }}
      build_image:
        description: "Workflow build image used for testing, i.e. registry + repository + tag"
        value: ${{ jobs.context.outputs.build_image }}
      build_labels:
        description: "Repository- and workflow-specific build labels"
        value: ${{ jobs.context.outputs.build_labels }}

jobs:
  context:
    runs-on: ubuntu-latest
    if: inputs.skip != 'all'
    permissions: {}
    outputs:
      chart_version: ${{ steps.get_context.outputs.chart_version }}
      original_registry: ${{ steps.get_context.outputs.original_registry }}
      original_repo: ${{ steps.get_context.outputs.original_repo }}
      original_image: ${{ steps.get_context.outputs.original_image }}
      original_tag: ${{ steps.get_context.outputs.original_tag }}
      build_registry: ${{ steps.get_context.outputs.build_registry }}
      build_repo: ${{ steps.get_context.outputs.build_repo }}
      build_tag: ${{ steps.get_context.outputs.build_tag }}
      ref_tags: ${{ steps.get_context.outputs.ref_tags }}
      build_image: ${{ steps.get_context.outputs.build_image }}
      build_labels: ${{ steps.get_context.outputs.build_labels }}
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Get context
        id: get_context
        uses: ./.github/actions/context

  build:
    runs-on: ubuntu-latest
    if: |
      inputs.skip != 'non-required' &&
      inputs.skip != 'all'
    needs: [context]
    permissions:
      id-token: write
      packages: write
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
      - name: Build semgr8s
        id: build
        uses: ./.github/actions/build
        with:
          image_registry: ${{ needs.context.outputs.build_registry }}
          image_repo: ${{ needs.context.outputs.build_repo }}
          image_tag: ${{ needs.context.outputs.build_tag }}
          ref_tags: ${{ needs.context.outputs.ref_tags }}
          image_labels: ${{ needs.context.outputs.build_labels }}
          repo_owner: ${{ github.repository_owner }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
