name: unit-test

#permissions: {}  #TODO: reactivate for non-private

on:
  workflow_call:
    inputs:
      skip:
        description: "Want to skip running certain jobs 'none', 'non-required', 'all'?"
        type: string
        default: "none"

jobs:
  gotest:
    name: unit tests
    runs-on: ubuntu-latest
    if: inputs.skip != 'all'
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Install
        run: |
          pip3 install -r tests/requirements.txt && pip3 install .
      - name: Test
        run: pytest --cov=semgr8s --cov-report=xml tests/
      - name: Upload
        uses: codecov/codecov-action@eaaf4bedf32dbdc6b720b63067d99c4d77d6047d # v3.1.4
        with:
          file: coverage.xml
