name: cleanup registry

on:
  workflow_call:

permissions: {}

jobs:
  cleanup-registry:
    runs-on: ubuntu-latest
    steps:
      - name: Cleanup test images
        uses: snok/container-retention-policy@3d27e6a0361deed0b7dc5099a82eadd07924b177 # v2.1.3
        with:
          image-names: semgr8s-test
          cut-off: three weeks ago UTC+1
          timestamp-to-use: updated_at
          account-type: org
          org-name: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
      - name: Cleanup dangling images without tag
        uses: snok/container-retention-policy@3d27e6a0361deed0b7dc5099a82eadd07924b177 # v2.1.3
        with:
          image-names: semgr8s*
          untagged-only: true
          cut-off: four hours ago UTC+1
          timestamp-to-use: updated_at
          account-type: org
          org-name: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
      - name: Cleanup all images
        uses: snok/container-retention-policy@3d27e6a0361deed0b7dc5099a82eadd07924b177 # v2.1.3
        with:
          image-names: semgr8s
          skip-tags: "main", "dev", "v*.*.*", "sha256-*"
          cut-off: four days ago UTC+1
          timestamp-to-use: updated_at
          account-type: org
          org-name: sse-secure-systems
          token: ${{ secrets.GHCR_PAT }}
