name: docs

permissions: {}

on:
  workflow_call:
    inputs:
      skip:
        description: "Want to skip running certain jobs 'none', 'non-required', 'all'?"
        type: string
        default: "none"

jobs:
  docs:
    runs-on: ubuntu-latest
    if: |
      (github.actor != 'dependabot[bot]') &&
      inputs.skip != 'all'
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
            fetch-depth: 0
      - name: Set release env
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Configure the git user
        run: |
          git config user.name "versioning_user"
          git config user.email "semgr8s@securesystems.de"
      - name: Install python
        uses: actions/setup-python@82c7e631bb3cdc910f68e0081d67478d79c6982d # v5.1.0
        with:
          python-version-file: '.python-version'
      - name: Install poetry
        uses: snok/install-poetry@93ada01c735cc8a383ce0ce2ae205a21c415379b # v1.3.4
        with:
          version: 1.8.3
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install dependencies
        run: |
          poetry install --only docs
      - name: Deploy
        if: inputs.skip != 'non-required'
        run: |
          if [[ "${GITHUB_REF}" == "refs/tags/v"* ]];
          then
            mike deploy --push --update-aliases ${RELEASE_VERSION} latest
          elif [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
            mike deploy --push ${RELEASE_VERSION}
          else
            mkdocs build
          fi
