name: unit-test

permissions:
  pull-requests: write

on:
  workflow_call:
    inputs:
      skip:
        description: "Want to skip running certain jobs 'none', 'non-required', 'all'?"
        type: string
        default: "none"

jobs:
  gotest:
    name: unit tests
    runs-on: ubuntu-latest
    if: inputs.skip != 'all'
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@0d103c3126aa41d772a8362f6aa67afac040f80c # v3.1.0
      - name: Build test image
        uses: docker/build-push-action@4a13e500e55cf31b7a5d59a38ab2040ab0f42f56 # v5.1.0
        with:
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: build/Dockerfile
          target: tester
          tags: semgr8s:tester
          provenance: false
          sbom: false
      - name: Test
        run: docker run --rm -t -v ${PWD}/tests/:/app/tests/ semgr8s:tester pytest --cov-report=term-missing:skip-covered --junitxml=tests/pytest.xml --cov=semgr8s tests/ | tee tests/pytest-coverage.txt
      - name: Coverage comment
        uses: MishaKav/pytest-coverage-comment@a1fe18e2b00c64a765568e2edb9f1706eb8fc88b # v1.1.51
        with:
          pytest-coverage-path: tests/pytest-coverage.txt
          junitxml-path: tests/pytest.xml
