name: unit-test

permissions:
  checks: write
  pull-requests: write

on:
  workflow_call:
    inputs:
      skip:
        description: "Want to skip running certain jobs 'none', 'non-required', 'all'?"
        type: string
        default: "none"

jobs:
  pytest:
    name: unit tests
    runs-on: ubuntu-latest
    if: inputs.skip != 'all'
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Set up Docker buildx
        uses: docker/setup-buildx-action@988b5a0280414f521da01fcc63a27aeeb4b104db # v3.6.1
      - name: Build test image
        uses: docker/build-push-action@5cd11c3a4ced054e52742c5fd54dca954e0edd85 # v6.7.0
        with:
          push: false
          load: true
          cache-from: type=gha
          cache-to: type=gha,mode=max
          file: build/Dockerfile
          target: tester
          tags: semgr8s:tester
          provenance: false
          sbom: false
      - name: Test
        run: docker run --rm -t -v ${PWD}/tests/:/app/tests/ semgr8s:tester pytest --cov-report=term-missing:skip-covered --junitxml=tests/pytest.xml --cov=semgr8s tests/ | tee tests/pytest-coverage.txt
      - name: Coverage comment
        id: comment
        uses: MishaKav/pytest-coverage-comment@fa1c641d7e3fa1d98ed95d5f658ccd638b774628 # v1.1.52
        if: |
          github.event_name == 'pull_request' &&
          inputs.skip != 'non-required'
        with:
          pytest-coverage-path: tests/pytest-coverage.txt
          junitxml-path: tests/pytest.xml
      - name: Publish Test Report
        uses: mikepenz/action-junit-report@db71d41eb79864e25ab0337e395c352e84523afe # v4.3.1
        if: success() || failure() # always run even if the previous step fails
        with:
          report_paths: 'tests/pytest.xml'
          fail_on_failure: true

  semgr8s-rules-validate:
    name: validate rules
    runs-on: ubuntu-latest
    if: |
      inputs.skip != 'all'
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Install python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version-file: '.python-version'
      - name: Install poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: 1.8.3
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install dependencies
        run: |
          poetry install --only main
      - name: Validate pre-configured rules
        run: |
          semgrep scan --metrics=off --validate --config ./charts/semgr8s/rules/
      - name: Validate additional rules
        run: |
          semgrep scan --metrics=off --validate --config ./rules/

  semgr8s-rules-test:
    name: test rules
    runs-on: ubuntu-latest
    if: |
      inputs.skip != 'all'
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - name: Install python
        uses: actions/setup-python@f677139bbe7f9c59b41e40162b753c062f5d49a3 # v5.2.0
        with:
          python-version-file: '.python-version'
      - name: Install poetry
        uses: snok/install-poetry@76e04a911780d5b312d89783f7b1cd627778900a # v1.4.1
        with:
          version: 1.8.3
          virtualenvs-create: false
          virtualenvs-in-project: false
          installer-parallel: true
      - name: Install dependencies
        run: |
          poetry install --only main
      - name: Test rules
        run: semgrep scan --metrics=off --test --config ./rules/ ./rules/tests/

