name: nightly-build

permissions: {}

on:
  schedule:
    - cron: "30 1 * * *"

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/.reusable-ci.yml
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      id-token: write
      issues: read
      packages: write
      pages: read
      pull-requests: write
      repository-projects: read
      security-events: write
      statuses: read
    secrets: inherit
    with:
      skip_build: 'none'
      skip_compliance_checks: 'all'
      skip_unit_tests: 'none'
      skip_sast: 'all'
      skip_sca: 'none'
      skip_docs: 'all'
      skip_integration_tests: 'non-required'
      output_type: 'sarif'
