name: nightly

permissions: {}

on:
  schedule:
    - cron: "30 1 * * *"

defaults:
  run:
    shell: bash

jobs:
  build:
    uses: ./.github/workflows/.reusable-build.yml
    permissions:
      id-token: write
      packages: write
    secrets: inherit
    with:
      skip: "non-required"

  compliance:
    uses: ./.github/workflows/.reusable-compliance.yml
    permissions:
      actions: read
      checks: read
      contents: write
      deployments: read
      discussions: read
      id-token: write
      issues: read
      packages: read
      pages: read
      pull-requests: read
      repository-projects: read
      security-events: write
      statuses: read
    secrets: inherit
    with:
      skip: "none"

  sca-released:
    name: sca (released)
    uses: ./.github/workflows/.reusable-sca.yml
    needs: [build]
    permissions:
      contents: write
      security-events: write
      packages: read
    secrets: inherit
    with:
      image: ${{ needs.build.outputs.original_image }}
      skip: "none"
      output: "table"

  cleanup-registry:
    uses: ./.github/workflows/.reusable-cleanup-registry.yml
    needs: [build]
    secrets: inherit
