name: push

#permissions: {}  #TODO: reactivate for non-private

on:
  push:
    branches:
      - main
      - dev

defaults:
  run:
    shell: bash

jobs:
  ci:
    uses: ./.github/workflows/.reusable-ci.yml
    #    permissions:  #TODO: adjust for non-private
    secrets: inherit
    with:
      #TODO: adjust for non private
      skip_build: 'none'
      skip_compliance_checks: 'none'
      skip_unit_tests: 'all'
      skip_sast: 'non-required'
      skip_sca: 'non-required'
      skip_docs: 'all'
      skip_integration_tests: 'all'
      output_type: 'sarif'
