name: Semgrep

permissions: {}

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  semgrep:
    name: semgrep policy
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'push') &&
      (github.actor != 'dependabot[bot]')
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - run: semgrep ci
