name: Semgrep

permissions: {}

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  semgrep:
    name: semgrep/ci
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'push') &&
      (github.actor != 'dependabot[bot]')
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29 # v4.1.6
      - run: semgrep ci
