name: Semgrep

permissions: {}

on:
  workflow_dispatch: {}
  workflow_call: {}

jobs:
  semgrep:
    name: semgrep policy
    runs-on: ubuntu-latest
    if: |
      (github.event_name != 'push') &&
      (github.actor != 'dependabot[bot]')
    env:
      SEMGREP_APP_TOKEN: ${{ secrets.SEMGREP_APP_TOKEN }}
    container:
      image: semgrep/semgrep
    steps:
      - uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
      - run: semgrep ci
