name: k8s-version-config
description: 'action to prepare testing different k8s versions'
inputs:
  k8s-version:
    description: 'k8s version to be tested'
    required: true
runs:
  using: "composite"
  steps:
    - name: Install yq and bash
      run: |
        sudo snap install yq
        sudo apt update
        sudo apt install bash -y
      shell: bash
    - uses: ./.github/actions/k3s-cluster
      with:
        k3s-channel: ${{ inputs.k8s-version }}
    - name: Adjust Configuration
      run: |
        if [[ $(echo "${{ inputs.k8s-version }}" | tail -c 3) -lt "19" ]]; then
          yq e 'del(.kubernetes.deployment.securityContext.seccompProfile)' -i charts/semgr8s/values.yaml
          yq e '.kubernetes.deployment.annotations."seccomp.security.alpha.kubernetes.io/pod" = "runtime/default"' -i charts/semgr8s/values.yaml
        fi
      shell: bash
